/* Generated by Together */

package dInternal.dTimeTable;

import dInternal.dData.SetOfResources;
import xml.InPut.ReadXMLElement;
import org.w3c.dom.Element;

public class Day {

  /**
   * Constructor
   * */
  public Day() {
    _setOfSequences = new SetOfResources(4);
  }

  /**
   * get the set of sequences
   * @return SetOfResources the set of sequences
   * */
  public SetOfResources getSetOfSequences(){
    return _setOfSequences;
  }

  /**
   * set the set of sequences
   * @param SetOfResources the set of sequences
   * */
  public void setSetOfSequences(SetOfResources setOfSequences){
    _setOfSequences= setOfSequences;
  }

  /**
    *
    * */
   public void readXMLtag(Element setofSeqs){
     ReadXMLElement list= new ReadXMLElement();
      Sequence setOfPeriods = new Sequence();
      String ID="";
      int size= list.getSize(setofSeqs,_TAGITEM);
      System.out.println(" Sequnces Size: "+size);//debug
      for (int i=0; i< size; i++){
        Element sequence= list.getElement(setofSeqs,_TAGITEM,i);
        ID= list.getElementValue(sequence,_TAGITEM1);
        System.out.println(" Sequences ID: "+ID);//debug
        Element periods= list.getElement(sequence,_TAGITEM2,0);
        setOfPeriods.readXMLtag(periods);
      }// end for (int i=0; i< size; i++)
   }


  private SetOfResources _setOfSequences;
  private String _TAGITEM="TTsequence";
  private String _TAGITEM1="sequenceID";
  private String _TAGITEM2="TTperiods";
}