/* Generated by Together */

package dInternal.dTimeTable;

import dInternal.dData.SetOfResources;
import dInternal.dUtil.DXObject;
public class Sequence extends DXObject {
    public Sequence() {
    }

    public SetOfResources getSetOfPeriods() {
        return new SetOfResources(4);
    }

    public void setSetOfPeriods(SetOfResources setOfPeriods) {
    }

    private SetOfPeriods _setOfPeriods;
}
