/* Generated by Together */

package dInternal.dTimeTable;

import dInternal.dData.SetOfResources;

public class SetOfSequences extends SetOfResources {
    public SetOfSequences() {
      super(4);
    }

    private Sequence _sequence;
}
