/* Generated by Together */

package dInternal.dTimeTable;

import dInternal.dData.SetOfResources;

public class SetOfSequences {

  /**
   * Constructor
   * */
  public SetOfSequences() {
    _setOfSequences = new SetOfResources(4);
  }

  /**
   * get the set of sequences
   * @return SetOfResources the set of sequences
   * */
  public SetOfResources getSetOfSequences(){
    return _setOfSequences;
  }

  /**
   * set the set of sequences
   * @param SetOfResources the set of sequences
   * */
  public void setSetOfSequences(SetOfResources setOfSequences){
    _setOfSequences= setOfSequences;
  }

  private SetOfResources _setOfSequences;
}