/* Generated by Together */

package dInternal.dTimeTable;

import dInternal.dData.SetOfResources;
public class SetOfPeriods extends SetOfResources {
    public SetOfPeriods() {
      super(4);
    }

    private Period _period;
}
