/* Generated by Together */

package dInternal.dTimetable;

import dInternal.dData.SetOfResources;
public class SetOfDays extends SetOfResources {
    public SetOfDays() {
    }

    private Day _day;
}
