/* Generated by Together */

package dInternal.dTimeTable;

import dInternal.dData.SetOfResources;
public class SetOfDays extends SetOfResources {
    public SetOfDays() {
      super(4);
    }


    private Day _day;
}
