/* Generated by Together */

package dInternal.dTimetable;

import dInternal.dData.SetOfResources;

/**
 * @author ysyam
 * @deprecated the root of the time table*/
public class TTStructure {
    public TTStructure() {
    }

 public SetOfResources getSetOfCycles() {
    return new SetOfResources();
 }

 public void setSetOfResources(SetOfResources setOfCycles) {
 }

 public String toWrite() {
    return "";
 }

 /**
  * @deprecated it contains a set of resources where _resourceObject is a Cycle object
  * @description it contains a set of resources where _resourceObject is a Cycle object*/
 private SetOfCycles _setOfCycles;

}
